In [278]:
import numpy as np
import pandas as pd

In [279]:
df=pd.read_csv('Countries.csv')
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [280]:
df.shape

(194, 64)

In [281]:
df.dtypes

country              object
country_long         object
currency             object
capital_city         object
region               object
                     ...
democracy_score     float64
democracy_type       object
median_age          float64
political_leader     object
title                object
Length: 64, dtype: object

In [282]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [283]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [284]:
df.isnull().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    7
title               7
Length: 64, dtype: int64

In [285]:
## how many countries doesn't have political_leaders

In [286]:
df.dropna(inplace=True)

In [287]:
df.isnull().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    0
title               0
Length: 64, dtype: int64

In [288]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
10,Azerbaijan,Republic of Azerbaijan,New Azeri manat,Baku,Western Asia,Asia,Azerbaijani,40.500000,47.500000,47801.00,...,10175016,18.33330,4357959,5817057,1.32,2.65,Authoritarian,27.9,Ilham Aliyev,President
12,Bangladesh,People's Republic of Bangladesh,Bangladeshi taka,Dhaka,Southern Asia,Asia,Bangladeshi,24.000000,90.000000,99010.00,...,171186372,20.85710,103206552,67979820,1.54,5.57,Hybrid regime,22.7,Sheikh Hasina,Prime Minister
19,Bolivia,Plurinational State of Bolivia,Bolivian Boliviano,Sucre,South America,Americas,Bolivian,-17.000000,-65.000000,377870.00,...,12224110,46.15380,3565773,8658337,2.21,5.70,Hybrid regime,20.1,Jeanine Áñez,President
22,Brazil,Federative Republic of Brazil,Brazilian real,Brasília,South America,Americas,Brazilian,-10.000000,-55.000000,2368790.00,...,215313498,17.73880,26795765,188517733,2.38,6.97,Flawed democracy,29.2,Jair Bolsonaro,President
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.00,...,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
35,Colombia,Republic of Colombia,Colombian peso,Bogotá,South America,Americas,Colombian,4.000000,-72.000000,482428.00,...,51874024,28.87700,9311387,42562637,1.83,6.96,Flawed democracy,27.2,Iván Duque,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.00,...,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.00,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
40,Croatia,Republic of Croatia,Croatian kuna,Zagreb,Southern Europe,Europe,Croatian,45.166667,15.500000,15050.00,...,3854000,31.78810,1610240,2243760,2.69,6.57,Flawed democracy,40.0,Andrej Plenković,Prime Minister
42,Cyprus,Republic of Cyprus,Euro,Nicosia,Southern Europe,Europe,Cypriot,35.000000,33.000000,1341.29,...,1251488,14.28570,414105,837383,3.60,7.59,Flawed democracy,34.1,Nicos Anastasiades,President
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.000000,25.000000,335720.00,...,99010212,12.80000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
52,El Salvador,Republic of El Salvador,U.S. dollar,San Salvador,Central America,Americas,Salvadoran,13.833333,-88.916667,11957.00,...,6336392,27.38100,1598862,4737530,2.62,5.96,Hybrid regime,22.8,Nayib Bukele,President
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.00,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
62,Georgia,Georgia,Georgian lari,Tbilisi,Western Asia,Asia,Georgian,42.000000,43.500000,23779.00,...,3712502,19.04760,1473975,2238527,2.70,5.50,Hybrid regime,32.5,Giorgi Gakharia,Prime Minister
67,Guatemala,Republic of Guatemala,Guatemalan quetzal,Guatemala City,Central America,Americas,Guatemalan,15.500000,-90.250000,38560.00,...,17357886,19.37500,8216182,9141704,2.18,5.60,Hybrid regime,18.5,Alejandro Giammattei,President
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.000000,77.000000,1790450.00,...,1417173173,14.94460,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.000000,120.000000,623000.00,...,275501339,21.91300,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
85,Kazakhstan,Republic of Kazakhstan,Kazakh tenge,Astana,Central Asia,Asia,Kazakhstani,48.000000,68.000000,2140030.00,...,19621972,27.35850,8243190,11378782,1.48,2.94,Authoritarian,25.5,Qasym-Zhomart Toqaev,President
90,Kyrgyz Republic,Kyrgyz Republic,Kyrgyz som,Bishkek,Central Asia,Asia,Kirghiz,41.000000,75.000000,103678.00,...,6803300,20.45450,4254716,2548584,2.61,5.11,Hybrid regime,19.8,Mukhammedkalyi Abylgaziev,Prime Minister
93,Lebanon,Lebanese Republic,Lebanese pound,Beirut,Western Asia,Asia,Lebanese,33.833333,35.833333,6696.70,...,5489739,6.25000,589488,4900251,2.41,4.63,Hybrid regime,24.6,Hassan Diab,Prime Minister
109,Mexico,United Mexican States,Mexican peso,Mexico City,Central America,Americas,Mexican,23.000000,-102.000000,971380.00,...,127504125,50.00000,23843271,103660854,1.67,6.19,Flawed democracy,25.4,Andrés Manuel López Obrador,President
117,Myanmar,Republic of the Union of Myanmar,Myanmar kyat,Naypyidaw,South-Eastern Asia,Asia,Burmese,22.000000,98.000000,130080.00,...,54179306,15.29410,36965999,17213307,1.74,3.83,Authoritarian,25.3,Win Myint,President
134,Peru,Republic of Peru,Peruvian new sol,Lima,South America,Americas,Peruvian,-10.000000,-76.000000,244783.00,...,34049588,40.00000,7249838,26799750,2.59,6.60,Flawed democracy,24.4,Martín Vizcarra,President
135,Philippines,Republic of the Philippines,Philippine peso,Manila,South-Eastern Asia,Asia,Filipino,13.000000,122.000000,126750.00,...,115559009,27.33120,60117263,55441746,1.78,6.71,Flawed democracy,20.8,Rodrigo Duterte,President
158,Sri Lanka,Democratic Socialist Republic of Sri Lanka,Sri Lankan rupee,Colombo,Southern Asia,Asia,Sri Lankan,7.000000,81.000000,28120.00,...,22181000,5.33333,17960843,4220157,1.97,6.19,Flawed democracy,28.8,Gotabaya Rajapaksa,President
162,Sudan,Republic of the Sudan,Sudanese pound,Khartoum,Northern Africa,Africa,Sudanese,15.000000,30.000000,694058.00,...,46874204,30.51640,30020115,16854089,1.08,2.15,Authoritarian,14.5,Abdel Fattah al-Burhan,Leader of the Sovereignty Council
169,Thailand,Kingdom of Thailand,Thai baht,Bangkok,South-Eastern Asia,Asia,Thai,15.000000,100.000000,230100.00,...,71697030,15.74640,33777188,37919842,1.77,4.63,Hybrid regime,35.8,Prayut Chan-o-cha,Prime Minister
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.000000,413110.00,...,38000000,20.33100,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President

In [289]:
df.dtypes

country              object
country_long         object
currency             object
capital_city         object
region               object
                     ...
democracy_score     float64
democracy_type       object
median_age          float64
political_leader     object
title                object
Length: 64, dtype: object

In [290]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [291]:
##country has highest population
df[df['population']==df['population'].max()]['country']

75    India
Name: country, dtype: object

In [292]:
##capital of the country with highest population
df[df['population']==df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [293]:
## capital of the country with least population
df[df['population']==df['population'].min()]['country']

42    Cyprus
Name: country, dtype: object

In [294]:
## to get the five highest country according to there democracy_score
df.nlargest(5,'democracy_score')['country']

42          Cyprus
75           India
22          Brazil
35        Colombia
135    Philippines
Name: country, dtype: object

In [295]:
df.sort_values('democracy_score',ascending=False).iloc[0:5]['country']

42          Cyprus
75           India
22          Brazil
35        Colombia
135    Philippines
Name: country, dtype: object

In [296]:
## check  how may unique regions are there
df['region'].nunique()

12

In [297]:
df['region'].value_counts().count()

np.int64(12)

In [300]:
## countries lie in eastern europe
df['region'].value_counts()['Eastern Europe']

np.int64(1)

In [ ]:
df[df['region']=='Eastern Europe'].value_counts().sum()

np.int64(1)

In [ ]:
df.loc[df.query("continent=='Africa'")['population'].idxmax()]

country                                            Ethiopia
country_long        Federal Democratic Republic of Ethiopia
currency                                     Ethiopian birr
capital_city                                    Addis Ababa
region                                       Eastern Africa
                                     ...
democracy_score                                        3.35
democracy_type                                Authoritarian
median_age                                             14.7
political_leader                                 Abiy Ahmed
title                                        Prime Minister
Name: 57, Length: 64, dtype: object

In [ ]:
## to check which has the country consists of the word republic
def check_republic(txt):
    s=txt.split()
    for i in s:
        if i =='Republic':
            return True
    return False

In [ ]:
df['country_long'].apply(
    check_republic
).sum()

np.int64(23)

In [ ]:
df['country_long'].str.contains('Republic').sum()

np.int64(23)

In [ ]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
10,Azerbaijan,Republic of Azerbaijan,New Azeri manat,Baku,Western Asia,Asia,Azerbaijani,40.5,47.5,47801.0,...,10175016,18.3333,4357959,5817057,1.32,2.65,Authoritarian,27.9,Ilham Aliyev,President
12,Bangladesh,People's Republic of Bangladesh,Bangladeshi taka,Dhaka,Southern Asia,Asia,Bangladeshi,24.0,90.0,99010.0,...,171186372,20.8571,103206552,67979820,1.54,5.57,Hybrid regime,22.7,Sheikh Hasina,Prime Minister
19,Bolivia,Plurinational State of Bolivia,Bolivian Boliviano,Sucre,South America,Americas,Bolivian,-17.0,-65.0,377870.0,...,12224110,46.1538,3565773,8658337,2.21,5.70,Hybrid regime,20.1,Jeanine Áñez,President
22,Brazil,Federative Republic of Brazil,Brazilian real,Brasília,South America,Americas,Brazilian,-10.0,-55.0,2368790.0,...,215313498,17.7388,26795765,188517733,2.38,6.97,Flawed democracy,29.2,Jair Bolsonaro,President
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.0,12.0,97500.0,...,27914536,33.8889,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President

In [ ]:
## country in africa has highest population in african region
df.loc[df[df['continent']=='Africa']['population'].idxmax()]

country                                            Ethiopia
country_long        Federal Democratic Republic of Ethiopia
currency                                     Ethiopian birr
capital_city                                    Addis Ababa
region                                       Eastern Africa
                                     ...
democracy_score                                        3.35
democracy_type                                Authoritarian
median_age                                             14.7
political_leader                                 Abiy Ahmed
title                                        Prime Minister
Name: 57, Length: 64, dtype: object

In [ ]:
## to get the 2nd highest country political leader
df.nlargest(2, 'population').iloc[-1]['political_leader']

'Joko Widodo'

In [ ]:
df.sort_values('population',ascending=False).iloc[1]['political_leader']

'Joko Widodo'